# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: e2e-test-app-job
# spec:
#   template:
#     metadata:
#       name: e2e-test-app-pod
#     spec:
#       containers:
#         - name: e2e-test-app
#           image: silomaben/cypress-tests
#           ports:
#             - containerPort: 80
#           imagePullPolicy: IfNotPresent
#       restartPolicy: Never

apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-test-app-job
spec:
  template:
    metadata:
      name: e2e-test-app-pod
    spec:
      containers:
      - name: e2e-test-app
        image: silomaben/cypress-tests
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
      - name: results-collector
        image: busybox:latest
        command: ["sh", "-c", "cp -r /app/* /test-results && sleep infinity"]
      # Replace with a command to collect and store results in the emptyDir
        volumeMounts:
        - name: test-results
          mountPath: /test-results
      volumes:
      - name: test-results
        emptyDir: {}
      restartPolicy: Never


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: e2e-test-app-job
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: e2e-test-app
#   template:
#     metadata:
#       labels:
#         app: e2e-test-app
#     spec:
#       containers:
#         - name: e2e-test-app
#           image: silomaben/cypress-tests
#           ports:
#             - containerPort: 80
#           imagePullPolicy: IfNotPresent
#       restartPolicy: Always
