apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-test-app-job
spec:
  template:
    metadata:
      name: e2e-test-app-pod
    spec:
      containers:
        - name: e2e-test-app
          image: silomaben/cypress-tests
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
      restartPolicy: Never

