# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cypress-reports-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: standard
#   hostPath:
#     path: /c/Users/BenardSilomaMasikond/Desktop/kubernetes/jenkinsData

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cypress-reports-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: standard




apiVersion: batch/v1
kind: Job
metadata:
  namespace: jenkins
  name: e2e-test-app-job
spec:
  template:
    metadata:
      name: e2e-test-app-pod
    spec:
      containers:
        - name: e2e-test-app
          image: silomaben/cypress-test
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home
      restartPolicy: Never
      volumes:
        - name: jenkins-vol
          persistentVolumeClaim: 
            claimName: jenkins-pv-claim


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: e2e-test-app-job
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: e2e-test-app
#   template:
#     metadata:
#       labels:
#         app: e2e-test-app
#     spec:
#       containers:
#         - name: e2e-test-app
#           image: silomaben/cypress-tests
#           ports:
#             - containerPort: 80
#           imagePullPolicy: IfNotPresent
#       restartPolicy: Always
