apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: internal-deployer-rb
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: internal-deployer
roleRef:
  kind: Role
  name: create-deployments
  apiGroup: rbac.authorization.k8s.io