apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /c/Users/BenardSilomaMasikond/Desktop/kubernetes/jenkinsData # Replace with your local path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext: #to  elevate user priviledge
        runAsUser: 0
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-vol
          persistentVolumeClaim: 
            claimName: jenkins-pv-claim
          
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins
# spec:
#   type: NodePort
#   ports:
#     - port: 8080
#       targetPort: 8080
#       nodePort: 30000
#   selector:
#     app: jenkins

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-jnlp
# spec:
#   type: ClusterIP
#   ports:
#     - port: 50000
#       targetPort: 50000
#   selector:
#     app: jenkins